package fits.stu.edu.vn.qlsv.domain;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sinhvien generated by hbm2java
 */
@Entity
@Table(name="sinhvien"
    ,catalog="qlsv"
)
public class Sinhvien  implements java.io.Serializable {


     private String mssv;
     private String hoten;
     private boolean phai;
     private Date ngaysinh;
     private float dtb;

    public Sinhvien() {
    }

    public Sinhvien(String mssv, String hoten, boolean phai, Date ngaysinh, float dtb) {
       this.mssv = mssv;
       this.hoten = hoten;
       this.phai = phai;
       this.ngaysinh = ngaysinh;
       this.dtb = dtb;
    }
   
     @Id 

    
    @Column(name="mssv", unique=true, nullable=false, length=4)
    public String getMssv() {
        return this.mssv;
    }
    
    public void setMssv(String mssv) {
        this.mssv = mssv;
    }

    
    @Column(name="hoten", nullable=false, length=40)
    public String getHoten() {
        return this.hoten;
    }
    
    public void setHoten(String hoten) {
        this.hoten = hoten;
    }

    
    @Column(name="phai", nullable=false)
    public boolean isPhai() {
        return this.phai;
    }
    
    public void setPhai(boolean phai) {
        this.phai = phai;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ngaysinh", nullable=false, length=10)
    public Date getNgaysinh() {
        return this.ngaysinh;
    }
    
    public void setNgaysinh(Date ngaysinh) {
        this.ngaysinh = ngaysinh;
    }

    
    @Column(name="dtb", nullable=false, precision=12, scale=0)
    public float getDtb() {
        return this.dtb;
    }
    
    public void setDtb(float dtb) {
        this.dtb = dtb;
    }




}



